<a href="https://colab.research.google.com/github/gautam16151/AZ-Static-Web/blob/wwwroot/Email_Security_AI_Model_v1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("/content/Phishing_Legitimate_full.csv")

Loading the Kaggle Phishing Dataset

In [6]:
print(df.shape)

(10000, 50)

In [7]:
print(df.columns)

Index(['id', 'NumDots', 'SubdomainLevel', 'PathLevel', 'UrlLength', 'NumDash',
       'NumDashInHostname', 'AtSymbol', 'TildeSymbol', 'NumUnderscore',
       'NumPercent', 'NumQueryComponents', 'NumAmpersand', 'NumHash',
       'NumNumericChars', 'NoHttps', 'RandomString', 'IpAddress',
       'DomainInSubdomains', 'DomainInPaths', 'HttpsInHostname',
       'HostnameLength', 'PathLength', 'QueryLength', 'DoubleSlashInPath',
       'NumSensitiveWords', 'EmbeddedBrandName', 'PctExtHyperlinks',
       'PctExtResourceUrls', 'ExtFavicon', 'InsecureForms',
       'RelativeFormAction', 'ExtFormAction', 'AbnormalFormAction',
       'PctNullSelfRedirectHyperlinks', 'FrequentDomainNameMismatch',
       'FakeLinkInStatusBar', 'RightClickDisabled', 'PopUpWindow',
       'SubmitInfoToEmail', 'IframeOrFrame', 'MissingTitle',
       'ImagesOnlyInForm', 'SubdomainLevelRT', 'UrlLengthRT',
       'PctExtResourceUrlsRT', 'AbnormalExtFormActionR', 'ExtMetaScriptLinkRT',
       'PctExtNullSelfRedirectHyperlinksRT', 'CLASS_LABEL'],
      dtype='object')

In [8]:
print(df.dtypes)

id                                      int64
NumDots                                 int64
SubdomainLevel                          int64
PathLevel                               int64
UrlLength                               int64
NumDash                                 int64
NumDashInHostname                       int64
AtSymbol                                int64
TildeSymbol                             int64
NumUnderscore                           int64
NumPercent                              int64
NumQueryComponents                      int64
NumAmpersand                            int64
NumHash                                 int64
NumNumericChars                         int64
NoHttps                                 int64
RandomString                            int64
IpAddress                               int64
DomainInSubdomains                      int64
DomainInPaths                           int64
HttpsInHostname                         int64
HostnameLength                          int64
PathLength                              int64
QueryLength                             int64
DoubleSlashInPath                       int64
NumSensitiveWords                       int64
EmbeddedBrandName                       int64
PctExtHyperlinks                      float64
PctExtResourceUrls                    float64
ExtFavicon                              int64
InsecureForms                           int64
RelativeFormAction                      int64
ExtFormAction                           int64
AbnormalFormAction                      int64
PctNullSelfRedirectHyperlinks         float64
FrequentDomainNameMismatch              int64
FakeLinkInStatusBar                     int64
RightClickDisabled                      int64
PopUpWindow                             int64
SubmitInfoToEmail                       int64
IframeOrFrame                           int64
MissingTitle                            int64
ImagesOnlyInForm                        int64
SubdomainLevelRT                        int64
UrlLengthRT                             int64
PctExtResourceUrlsRT                    int64
AbnormalExtFormActionR                  int64
ExtMetaScriptLinkRT                     int64
PctExtNullSelfRedirectHyperlinksRT      int64
CLASS_LABEL                             int64
dtype: object

In [9]:
print(df.isnull().sum())

id                                    0
NumDots                               0
SubdomainLevel                        0
PathLevel                             0
UrlLength                             0
NumDash                               0
NumDashInHostname                     0
AtSymbol                              0
TildeSymbol                           0
NumUnderscore                         0
NumPercent                            0
NumQueryComponents                    0
NumAmpersand                          0
NumHash                               0
NumNumericChars                       0
NoHttps                               0
RandomString                          0
IpAddress                             0
DomainInSubdomains                    0
DomainInPaths                         0
HttpsInHostname                       0
HostnameLength                        0
PathLength                            0
QueryLength                           0
DoubleSlashInPath                     0
NumSensitiveWords                     0
EmbeddedBrandName                     0
PctExtHyperlinks                      0
PctExtResourceUrls                    0
ExtFavicon                            0
InsecureForms                         0
RelativeFormAction                    0
ExtFormAction                         0
AbnormalFormAction                    0
PctNullSelfRedirectHyperlinks         0
FrequentDomainNameMismatch            0
FakeLinkInStatusBar                   0
RightClickDisabled                    0
PopUpWindow                           0
SubmitInfoToEmail                     0
IframeOrFrame                         0
MissingTitle                          0
ImagesOnlyInForm                      0
SubdomainLevelRT                      0
UrlLengthRT                           0
PctExtResourceUrlsRT                  0
AbnormalExtFormActionR                0
ExtMetaScriptLinkRT                   0
PctExtNullSelfRedirectHyperlinksRT    0
CLASS_LABEL                           0
dtype: int64

In [10]:
print(df.duplicated().sum())

0

In [12]:
print(df["CLASS_LABEL"].value_counts())

CLASS_LABEL
1    5000
0    5000
Name: count, dtype: int64

In [13]:
print(
    df["CLASS_LABEL"].value_counts(normalize=True) * 100
)

CLASS_LABEL
1    50.0
0    50.0
Name: proportion, dtype: float64

Reading the forst 5 rows of dataset

In [16]:
df.head()

,id,NumDots,SubdomainLevel,PathLevel,UrlLength,NumDash,NumDashInHostname,AtSymbol,TildeSymbol,NumUnderscore,...,IframeOrFrame,MissingTitle,ImagesOnlyInForm,SubdomainLevelRT,UrlLengthRT,PctExtResourceUrlsRT,AbnormalExtFormActionR,ExtMetaScriptLinkRT,PctExtNullSelfRedirectHyperlinksRT,CLASS_LABEL
0,1,3,1,5,72,0,0,0,0,0,...,0,0,1,1,0,1,1,-1,1,1
1,2,3,1,3,144,0,0,0,0,2,...,0,0,0,1,-1,1,1,1,1,1
2,3,3,1,2,58,0,0,0,0,0,...,0,0,0,1,0,-1,1,-1,0,1
3,4,3,1,6,79,1,0,0,0,0,...,0,0,0,1,-1,1,1,1,-1,1
4,5,3,0,4,46,0,0,0,0,0,...,1,0,0,1,1,-1,0,-1,-1,1

We will drop the id column as it is only and identifier and should not be used as a feature.

In [17]:
df = df.drop("id",axis=1)

In [18]:
print(df.shape)

(10000, 49)

separate the Features and Labels

In [19]:
x=df.drop("CLASS_LABEL", axis=1)
y=df["CLASS_LABEL"]
print(x.shape)
print(y.shape)

(10000, 48)
(10000,)

In [21]:
x.head()

,NumDots,SubdomainLevel,PathLevel,UrlLength,NumDash,NumDashInHostname,AtSymbol,TildeSymbol,NumUnderscore,NumPercent,...,SubmitInfoToEmail,IframeOrFrame,MissingTitle,ImagesOnlyInForm,SubdomainLevelRT,UrlLengthRT,PctExtResourceUrlsRT,AbnormalExtFormActionR,ExtMetaScriptLinkRT,PctExtNullSelfRedirectHyperlinksRT
0,3,1,5,72,0,0,0,0,0,0,...,0,0,0,1,1,0,1,1,-1,1
1,3,1,3,144,0,0,0,0,2,0,...,0,0,0,0,1,-1,1,1,1,1
2,3,1,2,58,0,0,0,0,0,0,...,0,0,0,0,1,0,-1,1,-1,0
3,3,1,6,79,1,0,0,0,0,0,...,1,0,0,0,1,-1,1,1,1,-1
4,3,0,4,46,0,0,0,0,0,0,...,0,1,0,0,1,1,-1,0,-1,-1

In [22]:
y.head()

0    1
1    1
2    1
3    1
4    1
Name: CLASS_LABEL, dtype: int64